### ISSUE TITLE
Training Manager

### ISSUE THREAD

**Issue by TheOriginalKoos** [MicrosoftDocs/AdaptiveCards#104]
Hi Team,

When will AdaptiveCards be available in Skype for Business?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87d1e8a9-5bad-9e08-a895-ad222e72d4dd
* Version Independent ID: 96e622ee-eea0-c487-e453-e1aad2cda1dd
* Content: [Adaptive Cards Overview - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/)
* Content Source: [AdaptiveCards/index.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/index.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by matthidinger** [comment]
Hi @TheOriginalKoos, Skype for Business is not on our roadmap at this time as Microsoft's investments on collaboration software is targeted at Microsoft Teams, which now fully supports adaptive cards. Hopefully the possibility of migrating will be an option for you!
