### ISSUE TITLE
Enhencement...

### ISSUE THREAD

**Issue by GearTheWorld** [MicrosoftDocs/AdaptiveCards#109]
When we change a property in the right pane for an object, let say an Action.OpenURL, nothing changes in the view until we go in the json payload and just change something there will trigger a refresh of the preview.  It would be good to make sure that the preview shows exactly what we change regardless where we change it.

[https://acdesignerstaging.azurewebsites.net/](url)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87d1e8a9-5bad-9e08-a895-ad222e72d4dd
* Version Independent ID: 96e622ee-eea0-c487-e453-e1aad2cda1dd
* Content: [Adaptive Cards Overview - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/)
* Content Source: [AdaptiveCards/index.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/index.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by matthidinger** [comment]
Thank you for reporting this! I've filed this issue here, hopefully we'll be able to roll it out soon. https://github.com/Microsoft/AdaptiveCards/issues/2102

FYI we have officially removed the "preview" tag from the designer and you can find it here:

https://adaptivecards.io/designer/
