### ISSUE TITLE
ChatBot in "talk to our Scuba Bot" link is not working

### ISSUE THREAD

**Issue by ikivanc** [MicrosoftDocs/AdaptiveCards#116]
When I click "talk to our Scuba Bot" link, I navigate to new link however embeded webUI for chat is not working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d5f1948-8ed0-f397-99ac-d10d8ae74d2b
* Version Independent ID: 63485280-4fee-678e-c5d4-5cd4b4dfd3bf
* Content: [Adaptive Cards for Bot Developers - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/getting-started/bots)
* Content Source: [AdaptiveCards/getting-started/bots.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/getting-started/bots.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by matthidinger** [comment]
This has been fixed, sorry about that!
