### ISSUE TITLE
I'm looking for something I don't find anywhere in all documentation.

### ISSUE THREAD

**Issue by GearTheWorld** [MicrosoftDocs/AdaptiveCards#117]
I'm doing a service app which will gather data from SQL and send an AC but I've been told to put the script in the head tag however how can I show the body html BEFORE the adaptive card because when in the head, I can't have the card after the html.

why I'm asking is because the customer wants to read the detail of the approval BEFORE going on and click Approve or Reject

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98b688c1-6a8f-b249-48a9-253e571bc177
* Version Independent ID: 6e703c95-f4ef-9baa-8dc5-801097a8cb8a
* Content: [Adaptive Cards in Outlook - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/getting-started/outlook)
* Content Source: [AdaptiveCards/getting-started/outlook.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/getting-started/outlook.md)
* Product: **adaptive-cards**
* GitHub Login: @dclaux
* Microsoft Alias: **dclaux**

**Comment by matthidinger** [comment]
If you're looking to delay showing the card until some later time you could wrap the card in a `<div style="display: none">[TheAdaptiveCard]</div>` and at some point later you could toggle the display to show it. Is that what you're asking?

**Comment by GearTheWorld** [comment]
Not exactly.  Since the payload is sent by email,  I already wrapped the card into an html page which the script is in the head tag.  Then the payload is sent using SMTP

**Comment by dclaux** [comment]
@GearTheWorld sorry but it is only possible to show the card above the HTML body. Outlook doesn't support showing the card below.

**Comment by GearTheWorld** [comment]
Ok I can live with that :(
