### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by himanshu143nith** [MicrosoftDocs/AdaptiveCards#120]
Instead of rendererdCard.Warnings; it must be renderedCard.Warnings;

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20a9d59f-d59c-47a4-2b41-389183c551ea
* Version Independent ID: b62496c8-3bf5-c148-c0b5-cfe25b520998
* Content: [Render a card - .NET HTML SDK - Adaptive Cards](https://docs.microsoft.com/en-gb/adaptive-cards/sdk/rendering-cards/net-html/render-a-card)
* Content Source: [AdaptiveCards/sdk/rendering-cards/net-html/render-a-card.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/sdk/rendering-cards/net-html/render-a-card.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by matthidinger** [comment]
Thanks! This will be fixed in the next publish
