### ISSUE TITLE
How to parse data from Action.Submit?

### ISSUE THREAD

**Issue by FRANZKAFKA13** [MicrosoftDocs/AdaptiveCards#121]
I am trying to use adaptive cards in a waterfall scenario to get a decision from the user. How can I use the adaptive card in prompts to parse the entered data? I use the "Action.Submit" action to send the data from the adaptive card to the bot. This dcoumentation (https://docs.microsoft.com/en-us/healthbot/scenario-authoring/adding-cards#getting-data-from-forms) talks about using the adaptive card in a prompt but I can't seem to leverage the sparse information. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09ccf460-83db-6fcf-e3ef-abaa4e5309b8
* Version Independent ID: 203350e2-2e23-f8f0-346a-f0e8e609c4c3
* Content: [Actions - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/rendering-cards/actions)
* Content Source: [AdaptiveCards/rendering-cards/actions.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/rendering-cards/actions.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by matthidinger** [comment]
Can you include the JSON you are using for the inputs? Are you rendering the cards yourself using something like WebChat, or using a client like Teams?

**Comment by FRANZKAFKA13** [comment]
This is my JSON file:
[JSONCard.txt](https://github.com/MicrosoftDocs/AdaptiveCards/files/2635832/JSONCard.txt)

I use the Bot Framework Emulator V4 for rendering.

This is how I call the card in the bot.js file:

        this.dialogSet.add(new WaterfallDialog('riskAssessment', [
            async function (step) {
                await step.context.sendActivity({
                    text: 'ABC',
                    attachments: [CardFactory.adaptiveCard(RiskCard)]
                }); 
            }
        ]));

**Comment by FRANZKAFKA13** [comment]
I found the solution. I had to read it from the step context's activity value:

this.dialogSet.add(new WaterfallDialog('riskAssessment', [
    async function (step) {

        await step.context.sendActivity({
            text: 'ABC',
            attachments: [CardFactory.adaptiveCard(RiskCard)]
        });
        
    },
    async function (step) {
        console.log("Choice");
        console.log(step.context.activity.value);
        // Returns: { choice_round1: '1a' } or { choice_round1: '1b' } 
    }
]));
