### ISSUE TITLE
Adaptive cards on Skype

### ISSUE THREAD

**Issue by MaoHasan** [MicrosoftDocs/AdaptiveCards#132]
When do you guys expect the adaptive cards to be ready on skype? got a couple of customers that saw it interesting and the limitation found was the unavailability on skype.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db11bc3a-be2d-998f-0bfa-b2d70a33f2ef
* Version Independent ID: c05ee199-ad86-0c01-c9bf-9b226f36c841
* Content: [Adaptive Cards Partners - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/resources/partners)
* Content Source: [AdaptiveCards/resources/partners.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/resources/partners.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by CodeOfConduct** [comment]
As Skype is not only a very popular tool for calling, but also widely used for messaging, it would be great to have Adaptive Cards working on Skype, too. The fact that Microsoft owns Skype should, in theory, make such an implementation even more sensible.

**Comment by andrewleader** [comment]
Thanks for your interest, we have no timelines to share at this time.
