### ISSUE TITLE
Can ChoiceSet Select default option by Title or Index

### ISSUE THREAD

**Issue by Ethanzj** [MicrosoftDocs/AdaptiveCards#143]
Currently, the ChoiceSet selects default option by value. If more than one option have the same value, it can only select the last option matches the value.  Can it select by Title which is usually unique? Or by index, which is guaranteed to be unique?

Here is our user case:
We use this choice set to select product. The Choice.Title is product and the Choice.value is the link. Many products map to same link. So we want the program select right product by default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4dc7404b-3d6c-01bc-568b-746835e4a471
* Version Independent ID: 8a4bacfa-deef-f1e2-74e4-41899ad3d409
* Content: [Card Schema - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/card-schema#inputchoiceset)
* Content Source: [AdaptiveCards/authoring-cards/card-schema.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/authoring-cards/card-schema.md)
* Product: **adaptive-cards**
* GitHub Login: @paulcam206
* Microsoft Alias: **paulcam**

**Comment by andrewleader** [comment]
Hey @Ethanzj, thanks for this feedback. No, ChoiceSet only selects by value. You could include some additional metadata in the value to make it unique. Let us know if that doesn't work for you!
