### ISSUE TITLE
Skype?

### ISSUE THREAD

**Issue by mmarinoNet** [MicrosoftDocs/AdaptiveCards#146]
When will Adaptive Cards be supported in Skype?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87d1e8a9-5bad-9e08-a895-ad222e72d4dd
* Version Independent ID: 96e622ee-eea0-c487-e453-e1aad2cda1dd
* Content: [Adaptive Cards Overview - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/#feedback)
* Content Source: [AdaptiveCards/index.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/index.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by matthidinger** [comment]
Hi @mmarinoNet, the Skype team is currently working on higher priority investments that their users are asking for, but as soon as I hear any more about their adaptive cards update I will be sure to report back
