### ISSUE TITLE
Adaptive Tools Designer should be listed here

### ISSUE THREAD

**Issue by jwittner** [MicrosoftDocs/AdaptiveCards#155]
Looking through the repo I found this: https://adaptivecards.io/designer/ Which is amazing and should be documented as one of, if not THE, tool to use. =)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cde9faa1-d627-7878-dc8c-d011ca1d7a79
* Version Independent ID: 13b04120-abf1-a545-bdaf-d3c919db14ea
* Content: [Adaptive Cards Tools - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/resources/tools)
* Content Source: [AdaptiveCards/resources/tools.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/resources/tools.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by matthidinger** [comment]
Thanks for the recommendation! I've added some content there :)
