### ISSUE TITLE
This schema should provide the possible values for the properties.

### ISSUE THREAD

**Issue by jwittner** [MicrosoftDocs/AdaptiveCards#157]
Right now I feel like I have to scrounge around the non-reference for what values are allowed or I have to look to the designer and try it out. Would be nice to have a one stop shop for reference documentation. =)

E.g. What values can I set as TextBlock.weight?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4dc7404b-3d6c-01bc-568b-746835e4a471
* Version Independent ID: 8a4bacfa-deef-f1e2-74e4-41899ad3d409
* Content: [Card Schema - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/card-schema#textblock)
* Content Source: [AdaptiveCards/authoring-cards/card-schema.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/authoring-cards/card-schema.md)
* Product: **adaptive-cards**
* GitHub Login: @paulcam206
* Microsoft Alias: **paulcam**

**Comment by andrewleader** [comment]
Hey @jwittner, thanks for this feedback, we've implemented displaying the values that are allowed! The card schema is now only displayed on https://adaptivecards.io/explorer/ which displays allowed enum values and more :)
