### ISSUE TITLE
Provide Examples

### ISSUE THREAD

**Issue by atishayv** [MicrosoftDocs/AdaptiveCards#160]
Can you please provide examples/sample code on how we can use this extensibility feature to override the rendering of any element or add support for entirely new elements in this document ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac42ea50-480b-a136-27fc-171c83470788
* Version Independent ID: 330017d6-8292-34ec-dce8-668a02660a71
* Content: [Extensibility - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/rendering-cards/extensibility#feedback)
* Content Source: [AdaptiveCards/rendering-cards/extensibility.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/rendering-cards/extensibility.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by matthidinger** [comment]
Thanks for the feedback here! I've updated the content to explain where to find the relevant SDK docs. 

For example, see here for the JavaScript docs: https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/javascript/extensibility

**Comment by atishayv** [comment]
Thanks..
