### ISSUE TITLE
Prevent redundant submissions

### ISSUE THREAD

**Issue by GeneralChenChen** [MicrosoftDocs/AdaptiveCards#177]
Currently there's no restriction on how many times you can click on a card and submit data. Is it possible to add a functionality to prevent redundant submissions? While we can handle this on server side, it'll be much simpler and cleaner if we can configure the card and prevent it from client side.

There are two scenarios I can think of:
1. Prevent redundant submission for a single button
2. Prevent redundant submission for the whole card (i.e. if any element has already submitted, the whole card will not submit again)

I think it should be possible if we add some options to the schema of Action.Submit. 

Thoughts?

**Comment by andrewleader** [comment]
Hi GeneralChenChen,

With most platforms that you can send cards to (Teams, Outlook, WebChat), when a user submits an action, you can update the card. You could then update the card removing the buttons.
