### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/AdaptiveCards#191]
This page needs to be update. I know Web Chat at least supports Adaptive Cards 1.1. Do any partners support 1.2?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db11bc3a-be2d-998f-0bfa-b2d70a33f2ef
* Version Independent ID: c05ee199-ad86-0c01-c9bf-9b226f36c841
* Content: [Adaptive Cards Partners - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/resources/partners)
* Content Source: [AdaptiveCards/resources/partners.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/resources/partners.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by andrewleader** [comment]
Thanks, Web Chat has been updated to 1.2 now that it has just been released on Web Chat!
