### ISSUE TITLE
Missing style property

### ISSUE THREAD

**Issue by patgoley** [MicrosoftDocs/AdaptiveCards#192]
This page does not document the action "style" property that is shown in the editor.

Also, I don't see any way to change the color of action buttons based on the "style" property. Not sure if that would be on this page or somewhere else.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09ccf460-83db-6fcf-e3ef-abaa4e5309b8
* Version Independent ID: 203350e2-2e23-f8f0-346a-f0e8e609c4c3
* Content: [Actions - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/rendering-cards/actions#feedback)
* Content Source: [AdaptiveCards/rendering-cards/actions.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/rendering-cards/actions.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by andrewleader** [comment]
Hey @pategoley, the page you commented on isn't supposed to be schema documentation of actions. It talks about actions from the renderer side. The schema docs are in the schema explorer, and `style` is documented there: https://adaptivecards.io/explorer/Action.OpenUrl.html

As for changing the color of actions based on the `style`, only the **host** application (the one rendering the cards) can choose the colors. So if you're simply sending cards to Microsoft Teams or Outlook, you can't control those colors. But if you're rendering cards yourself (like with WebChat or directly using our SDKs), then you can choose the color that corresponds with each style. If you're rendering cards yourself and would like to know how to customize those colors, let me know!
