### ISSUE TITLE
Render issue in adaptive cards

### ISSUE THREAD

**Issue by nis92009** [MicrosoftDocs/AdaptiveCards#194]
hi

Static json renders perfectly  but not able to render the json from controller,,, their is no error nothing,,,but adaptive ,js also loads but on browser nothing is displayed ,   if any one can send me a basic sample working code which send json data from server to browser,
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a3cca2e-25b8-8f9b-bbdc-51ecc941bda3
* Version Independent ID: 45ea6e8f-7f2d-5248-0ec9-cb37905cf318
* Content: [Render a card - JavaScript SDK - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/javascript/render-a-card#feedback)
* Content Source: [AdaptiveCards/sdk/rendering-cards/javascript/render-a-card.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/sdk/rendering-cards/javascript/render-a-card.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by andrewleader** [comment]
Hi @nis92009, [StackOverflow](https://stackoverflow.com/questions/tagged/adaptive-cards) is where you should ask technical questions. Also, we'll need more details about what specifically is failing, what you're trying, etc. Thanks!
