### ISSUE TITLE
Using the object model for creating cards example does not pass type check

### ISSUE THREAD

**Issue by petmat** [MicrosoftDocs/AdaptiveCards#195]
I'm trying to create a card with TypeScript using the exactly same example code as in this document under the text "There is also an object model for creating cards".

The first line causes this error: "Property 'type' is missing in type 'AdaptiveCard' but required in type 'IAdaptiveCard'. ts(2741)"

And the second line also has an error: "Property 'add' does not exist on type '(ITextBlock | IImage | IImageSet | IFactSet | IColumnSet | IContainer)[]'. ts(2339)"

Even the object initializer throws an error: "Cannot find name 'text'. Did you mean 'Text'? ts(2552)"

Has this example been tested and verified that it is actually supposed to work?

I'm using TypeScript 3.5.1 and adaptivecards 1.2.0.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd612476-bf3f-c213-fdfa-3ef4069dfe02
* Version Independent ID: 8f7e10aa-6fc1-3804-5b46-d83494f400a7
* Content: [JavaScript SDK for Adaptive Cards - Adaptive Cards](https://docs.microsoft.com/en-gb/adaptive-cards/sdk/authoring-cards/javascript#feedback)
* Content Source: [AdaptiveCards/sdk/authoring-cards/javascript.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/sdk/authoring-cards/javascript.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by nathanlindorff** [comment]
I have also encountered the same issue. The interface and the class seem to be incompatible.

**Comment by matthidinger** [comment]
Sorry about that folks, indeed the previous source code was incorrect. I've updated the example with the correct API and removed the section about the schema typings, which as of not aren't a supported means for creating cards. Any feedback welcome
