### ISSUE TITLE
Outlook Client and Version 1.2

### ISSUE THREAD

**Issue by aruntd77** [MicrosoftDocs/AdaptiveCards#200]
Hi,

I am using v1.2 schema. Card is displayed in Web outlook (OWA), but styles are not rendering correctly (for example container style set to "accent" does not set the background color to sky blue). 

And same message if viewed in Outlook client, the card does not show up. 

However if using v1.0, Outlook client shows the card and web outlook also shows the card. Since I dont have choice to use more style themes in 1.0, I was trying to use v1.2. 

Is there any limitations for Outlook clients to use v1.2?

**Comment by matthidinger** [comment]
Hi @aruntd77, currently Outlook supports v1.0 of the schema but we are working with our partners to update them to latest versions as soon as they can. Keep an eye on the [Partner Status](https://docs.microsoft.com/en-us/adaptive-cards/resources/partners) to see what version of the schema is supported where
