### ISSUE TITLE
A typo

### ISSUE THREAD

**Issue by kkomelin** [MicrosoftDocs/AdaptiveCards#202]
&gt; Our vision is to create a shared ecosystem **were** developers can write and share...

Where "were" should be "where", I think.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db11bc3a-be2d-998f-0bfa-b2d70a33f2ef
* Version Independent ID: c05ee199-ad86-0c01-c9bf-9b226f36c841
* Content: [Adaptive Cards Partners - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/resources/partners#live)
* Content Source: [AdaptiveCards/resources/partners.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/resources/partners.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by matthidinger** [comment]
Thanks! This has been fixed
