### ISSUE TITLE
Docs are outdated

### ISSUE THREAD

**Issue by FrankJWong** [MicrosoftDocs/AdaptiveCards#214]
Doing (literally) this code will work but gives a warning:
"'AdaptiveCard.AdaptiveCard()' is obsolete: 'Please use the overload that accepts a version parameter and specify the version your card requires'"

Clicking on "Show Potential Fixes" shows none.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20a9d59f-d59c-47a4-2b41-389183c551ea
* Version Independent ID: b62496c8-3bf5-c148-c0b5-cfe25b520998
* Content: [Render a card - .NET HTML SDK - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/net-html/render-a-card#feedback)
* Content Source: [AdaptiveCards/sdk/rendering-cards/net-html/render-a-card.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/sdk/rendering-cards/net-html/render-a-card.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by matthidinger** [comment]
Updated the docs in the latest push to include the new signature

**Comment by uncheckederror** [comment]
@matthidinger This issue appears to have been closed prematurely. The obsolete warning persists as of Visual Studio 2019 version 16.5.1.

This code snippet is throwing the warning:
 ```cs
    // Build a simple card
    // In the real world this would probably be provided as JSON
    AdaptiveCard card = new AdaptiveCard()
    {
        Body = { new AdaptiveTextBlock() { Text = "Hello World" } }
    };
```
If you were to modify this documentation to use the following code instead, Visual Studio 2019 will no longer throw this warning:

```cs
    var schemaVersion = renderer.SupportedSchemaVersion; 
    var newCard = new AdaptiveCard(schemaVersion)
    {
        Body = { new AdaptiveTextBlock() { Text = "Hello World" } }
    };
```
Thanks!
