### ISSUE TITLE
ConnectorCard: Links with "tel:" schema fail to render correctly.

### ISSUE THREAD

**Issue by LeoniePhiline** [MicrosoftDocs/AdaptiveCards#216]
Example:
```
**Someone called** ([0123456789](tel:+31123456789))
```

Microsoft Teams renders this (sent via incoming Webhook) incorrectly:
```
&lt;p&gt;&lt;strong&gt;Someone called&lt;/strong&gt; (&lt;a target="_blank" rel="noreferrer noopener"&gt;0123456789&lt;/a&gt;)&lt;/p&gt;
```
The `href` attribute is missing entirely.

Furthermore, `potentialAction` elements of `@type` `'OpenUri'` with a `tel:+31123456789` URI are not rendered at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc130656-2e47-da15-cf41-40bc9661b592
* Version Independent ID: 127c1432-3f3b-8056-4b25-6fd19be5e40f
* Content: [Text Features - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/text-features#feedback)
* Content Source: [AdaptiveCards/authoring-cards/text-features.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/authoring-cards/text-features.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by LeoniePhiline** [comment]
Oh, this feedback form seems to double-encode htmlentities...

**Comment by LeoniePhiline** [comment]
This is even the case if formatting with plain HTML in the card `text` field:
```html
<a href="tel:+31123456798">0123456789</a>
```
gets rendered inside a Teams channel card as:
```html
<a target="_blank" rel="noreferrer noopener">06 10774086</a>
```
So there is no clickable link.

**Comment by LeoniePhiline** [comment]
Bug report added to https://microsoftteams.uservoice.com/forums/908686-bug-reports/suggestions/38621044-support-tel-links-in-webhook-cards

**Comment by matthidinger** [comment]
Hi Leonie, thanks for reporting and filing the User Voice issue. What you describe seems to be an issue with "MessageCard" which was a precursor to Adaptive Cards. Currently there is no way to use Adaptive Cards in webhooks. The UserVoice bug will likely be your best way to track this. Please do reopen if you think this may be incorrect or have other questions
