### ISSUE TITLE
new AdaptiveCard() is obsolete

### ISSUE THREAD

**Issue by Blackbaud-ChristiSchneider** [MicrosoftDocs/AdaptiveCards#218]
This example uses an obsolete constructor.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4461e3d-c008-2db2-9411-18c687c06e41
* Version Independent ID: 1b5c2925-a111-be5f-9d28-22d12bcdff85
* Content: [.NET SDK for Adaptive Cards - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/sdk/authoring-cards/net#feedback)
* Content Source: [AdaptiveCards/sdk/authoring-cards/net.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/sdk/authoring-cards/net.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by matthidinger** [comment]
Thanks for reporting! Should be fixed in the next few minutes
