### ISSUE TITLE
Outlook actionable message - Target URL not allowed

### ISSUE THREAD

**Issue by Geradav** [MicrosoftDocs/AdaptiveCards#222]
Hi Team,

I'm currently working on an approval flow using Outlook actionable message.

I have created an Outlook actionable message via Ms Flow and registered it on the "Actionable Email Developer Dashboard" with "scope of submission" -> 'Organization'

The email containing the actionable message is received by different company members and renders correctly. However, when clicking to take any action I get the following message => "Target URL <...> is not allowed"

All previous tests worked very well when messages were sent from my email to my email. I could take action and update the message. But now it does not work anymore.

Here are the different steps:

- The requester fills a form in a model-driven app (PowerApps)
- The requester then click on a custom button in the Model-Driven app to trigger a Flow HTTP Request
- An email actionable message is then sent to the appropriate person to take action Until that step, all good, no problem.

Then the person receiving the email can click on the actionable message to take action. The message contains an 'approve' button that should trigger a Flow HTTP Request That's where the problem is... It never triggers the Flow and the error message shows "Target URL ... is not allowed" All Flows have been shared with all parties. Both actions have been registered on the "Actionable Email Developer Dashboard"

In the JSON object the token has been placed as the value for the 'Originator' key
```
"actions": [
{
"type": "Action.Http",
"title": "Send",
"method": "POST",
"url": "https://prod-00.westus.logic.azure.com:999/workflows<...>",
"body": "{\"comment\":\"{{ApproveComment.value}}\"}",
"headers": [
{
"name": "Authorization",
"value": ""
}
]
}
],
"$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}
},
```
The object that should trigger the second Flow HTTP Request is as the snippet above, with a 'headers' key and 'Authorization', 'value' set to an empty string.

So, what did I do wrong? What should I do to have the second Flow working?

Thanks for the help

**Comment by matthidinger** [comment]
Hi @Geradav, sorry for the delay on here. I reached out to folks on the Actionable Messages team and they said they've resolved your issue. I'll close this, but please reopen if you're still having any problems!
