### ISSUE TITLE
Rendering card for the above JavaScript example(Templating) or AdaptiveCards template to send dynamic data.

### ISSUE THREAD

**Issue by AravindR7** [MicrosoftDocs/AdaptiveCards#223]
Wanted to test the above example in Emulator, How do I render the card for the above example?

How do I send dynamic data using adaptive card template?

-------------------------------------------------------------------------------------------------------------------------------
```js
import * as ACData from "adaptivecards-templating";
import * as AdaptiveCards from "adaptivecards";
 
// Define a template payload
var templatePayload = {
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "Hello {name}!"
        }
    ]
};
 
// Create a Template instamce from the template payload
var template = new ACData.Template(templatePayload);
 
// Create a data binding context, and set its $root property to the
// data object to bind the template to
var context = new ACData.EvaluationContext();
context.$root = {
    "name": "Mickey Mouse"
};
 
// "Expand" the template - this generates the final Adaptive Card,
// ready to render
var card = template.expand(context);
 
// Render the card
var adaptiveCard = new AdaptiveCards.AdaptiveCard();
adaptiveCard.parse(card);
 
var htmlElement = adaptiveCard.render()
```

Should I add  above code in a separate dialog and  render it or is it dirictely possible to test it out in emulator?

How to populate the template with real data?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b499287b-06d7-456f-5d15-e50c954ace35
* Version Independent ID: be6accea-502b-6340-c71a-f92d43ce87f5
* Content: [Templating SDKs - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/templating/sdk#feedback)
* Content Source: [AdaptiveCards/templating/sdk.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/templating/sdk.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by matthidinger** [comment]
Great! Let us know if you have any other troubles or feedback!
