### ISSUE TITLE
Custom Adaptive Card not showing in Microsoft Teams iOS App

### ISSUE THREAD

**Issue by mkulgeorge** [MicrosoftDocs/AdaptiveCards#232]
Hi Team,

I created a adaptive card using the adaptivcard.io, I used that in the a chatbot to send the data to Microsoft Teams.
This card gets displayed very perfectly in the Microsoft Teams desktop app.
However the card is not displayed in the Microsoft Teams iOS App.

Here is the adaptive card, its data and the screen shot of how it is displayed in the Microsoft Teams desktop app.

{
        "type": "AdaptiveCard",
        "version": "1.0",
        "body": [
            {
                "type": "Container",
                "items": [
                    {
                        "type": "TextBlock",
                        "text": "{commandHeader}",
                        "size": "ExtraLarge",
                        "color": "Good",
                        "id": "commandHeader"
                    }
                ],
                "separator": true,
                "style": "warning"
            },
            {
                "type": "Container",
                "items": [
                    {
                        "type": "ColumnSet",
                        "columns": [
                            {
                                "type": "Column",
                                "width": "stretch",
                                "items": [
                                    {
                                        "type": "TextBlock",
                                        "text": "{$data.command}",
                                        "weight": "Bolder",
                                        "color": "Good"
                                    }
                                ],
                                "style": "emphasis"
                            },
                            {
                                "type": "Column",
                                "width": "stretch",
                                "items": [
                                    {
                                        "type": "TextBlock",
                                        "text": "{$data.description}",
                                        "wrap": true
                                    }
                                ],
                                "style": "default",
                                "verticalContentAlignment": "Center"
                            }
                        ]
                    }
                ],
                "id": "top",
                "$data": "{commandList}"
            }
        ],
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
    }

Here is the data for this card.

{
                "commandHeader" : "Bot Commands",
                "commandList" : [
                            {
                                "command": "MY_CUSTOMER_ORDERS",
                                "description": "This command will start a dialog to get the data required to get the List of orders for the customer you are assinged to"
                            },
                            {
                                "command": "TEST_BOT",
                                "description": "Bot to test new developments"
                            },
                            {
                                "command": "CUSTOM_DIALOG",
                                "description": "Bot to build and test custom dialogs creation without using the dialog module"
                            },
                            {
                                "command": "USER_PROFILE_DIALOG",
                                "description": "Bot to test the dialog storage and retrival"
                            },
                            {
                                "command": "DYNAMIC_DIALOG",
                                "description": "Bot to test the creation of dynamic dialogs using configuration"
                            }
                        ]
            }

This is how it looks in Teams,

![image](https://user-images.githubusercontent.com/28863199/68538533-db2a0600-039b-11ea-8061-a8647d4201b4.png)

Here is the code which send the adaptive card.

` // Adaptive Card for command List
            const { Template , EvaluationContext} = require('adaptivecards-templating');
            // const { AdaptiveCard } = require ('adaptivecards');
         
            // The card template 
            var templatePayload = CommandListCard;
            
            // Create a Template instance from the template payload
            var template = new Template(templatePayload);
            
            // Create a data binding context, and set its $root property to the
            // data object to bind the template to
            var context = new EvaluationContext();
            context.$root = {
                "commandHeader" : "Bot Commands",
                "commandList" : [
                            {
                                "command": "MY_CUSTOMER_ORDERS",
                                "description": "This command will start a dialog to get the data required to get the List of orders for the customer you are assinged to"
                            },
                            {
                                "command": "TEST_BOT",
                                "description": "Bot to test new developments"
                            },
                            {
                                "command": "CUSTOM_DIALOG",
                                "description": "Bot to build and test custom dialogs creation without using the dialog module"
                            },
                            {
                                "command": "USER_PROFILE_DIALOG",
                                "description": "Bot to test the dialog storage and retrival"
                            },
                            {
                                "command": "DYNAMIC_DIALOG",
                                "description": "Bot to test the creation of dynamic dialogs using configuration"
                            }
                        ]
            };
            
            // "Expand" the template - this generates the final Adaptive Card,
            // ready to render
            var cardTemplate = template.expand(context);
            // var adaptiveCard = new AdaptiveCard();
            
            const card = CardFactory.adaptiveCard(cardTemplate);
            // const card = adaptiveCard.parse(card);
            await turnContext.sendActivity({ attachments: [card] });  
`

**Comment by nesalang** [comment]
@mkulgeorge,

hello,

templating is currently not supported for ios.

**Comment by dclaux** [comment]
@mkulgeorge your card uses a 1.2 Adaptive Card feature (name, the "warning" container style.) Teams desktop now supports Adaptive Cards 1.2, but Teams for iOS (and Android) doesn't yet support it (and currently supports 1.0 only.) That is likely why your card isn't showing on iOS.

Try removing "style": "warning" from your top container.

**Comment by dclaux** [comment]
BTW I assume you do the binding prior to sending the card, so templating shouldn't be the problem here - no Teams client currently support client-side templating anyway.

**Comment by nesalang** [comment]
> **BTW I assume you do the binding prior to sending the card**, so templating shouldn't be the problem here - no Teams client currently support client-side templating anyway.

good catch David.

**Comment by mkulgeorge** [comment]
@dclaux 
Does this means that I cannot use the {$data} and I should build the JSON with completely and send it?
