### ISSUE TITLE
source code availability

### ISSUE THREAD

**Issue by IntranetFactory** [MicrosoftDocs/AdaptiveCards#255]
&gt; we will open source once we tie up some loose ends.

Any ETA for open source release?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f75b364-ca09-ef9e-ca29-9b33ed8ff58f
* Version Independent ID: 71d36281-021b-d499-394f-da760c225d02
* Content: [Adaptive Cards Template Service - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/templating/service#feedback)
* Content Source: [AdaptiveCards/templating/service.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/templating/service.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by matthidinger** [comment]
Whoops I need to update these docs, in fact it is open source now. Please see https://github.com/Microsoft/adaptivecards-templates

Let us know if you have any feedback!
