### ISSUE TITLE
ETA Number & Date functions

### ISSUE THREAD

**Issue by IntranetFactory** [MicrosoftDocs/AdaptiveCards#256]
Do you have any ETA for number and date functions? Without being able to insert dates and numbers in the users locale most of our use case are not yet possible :-(

Are there any plans to make the source code of both version available in the near future?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 117f7457-f439-e41e-8782-ff627e6b030b
* Version Independent ID: 22f86ac6-47f8-447f-82e9-8093b3ddf0fb
* Content: [Adaptive Cards Template Language - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/templating/language)
* Content Source: [AdaptiveCards/templating/language.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/templating/language.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by matthidinger** [comment]
Hi @IntranetFactory, these functions are now available and part of the v1.0 release. Functions are now available and linked below, please let us know if this doesn't meet your needs!

Built-in functions: https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0
