### ISSUE TITLE
Licensing for rendering Adaptive Cards

### ISSUE THREAD

**Issue by cactusme** [MicrosoftDocs/AdaptiveCards#278]
I am interested in rendering Adaptive Card in my own application.  Is there licensing needed if I want to do my own rendering of an Adaptive Card?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db11bc3a-be2d-998f-0bfa-b2d70a33f2ef
* Version Independent ID: c05ee199-ad86-0c01-c9bf-9b226f36c841
* Content: [Adaptive Cards Partners - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/resources/partners#feedback)
* Content Source: [AdaptiveCards/resources/partners.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/resources/partners.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by matthidinger** [comment]
Hi there, the license is MIT can be found here: https://github.com/microsoft/AdaptiveCards/blob/master/LICENSE

Please reopen if this doesn't address your issue :)
