### ISSUE TITLE
Objective-C syntax errors

### ISSUE THREAD

**Issue by tomhamming** [MicrosoftDocs/AdaptiveCards#282]
In "Create a card from a JSON string", you have this snippet:

```
NSString *jsonStr = @"{ \"type\": \"AdaptiveCard\", \"version\": \"1.0\", \"body\": [ { \"type\": \"Image\", \"url\": \"http://adaptivecards.io/content/adaptive-card-50.png\", \"horizontalAlignment\":\"center\" }, { \"type\": \"TextBlock\", \"horizontalAlignment\":\"center\", \"text\": \"Hello **Adaptive Cards!**\" } ], \"actions\": [ { \"type\": \"Action.OpenUrl\", \"title\": \"Learn more\", \"url\": \"http://adaptivecards.io\" }, { \"type\": \"Action.OpenUrl\", \"title\": \"GitHub\", \"url\": \"http://github.com/Microsoft/AdaptiveCards\" } ] }";
ACOAdaptiveCardParseResult *cardParseResult = [ACOAdaptiveCard fromJson:jsonStr];

/// access for parse warnings and errors
NSArray<NSError *> errors = cardParseResult.parseErrors;
NSArray<ACRParseWarning *> warnings = cardPraseResult.parseWarnings;
```

The declarations of the arrays are missing pointer indicators (`*errors`, `*warnings`). And on the last line, it should be `cardParseResult`, not `cardPraseResult`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ce0e193-c769-b02b-666c-2aba9f871e1b
* Version Independent ID: 84d6f993-8382-5ea1-594a-6239132947cf
* Content: [Render a card - iOS SDK - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/ios/render-a-card#feedback)
* Content Source: [AdaptiveCards/sdk/rendering-cards/ios/render-a-card.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/sdk/rendering-cards/ios/render-a-card.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by tomhamming** [comment]
Also, under "Render a Card", `renderResult` should be initialized as `nil` to avoid a compiler warning:

```
ACRRenderResult *renderResult = nil;
if(cardParseResult.isValid){
    renderResult = [ACRRenderer render:cardParseResult.card config:nil widthConstraint:335];
}
```

**Comment by jwoo-msft** [comment]
@tomhamming 
Thanks for reporting this.
