### ISSUE TITLE
Time formatting changed in updated SDK

### ISSUE THREAD

**Issue by erwelch** [MicrosoftDocs/AdaptiveCards#294]
There is no documentation here for how to update using the [Date/time](https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/text-features#datetime-formatting-and-localization) formatting with the new release of the SDK. In fact, it seems this might be completely broken now with the new `Expand` method. 

When I attempt to format using a template following the strict RFC 3389 formatting it doesn't work because my date formatted like this: `2020-06-02T16:43:48Z` gets translated in the new `Expand()` method to look like this: `6/2/2020 4:43:48 PM`. 

So this block:

```
 {
       "type": "TextBlock",
       "spacing": "None",
       "text": "Paused at {{TIME(${pausedUtc})}}",
       "isSubtle": true,
       "wrap": true
}
```

Ends up looking like this in the card:
```
Paused at {{TIME(6/2/2020 4:43:48 PM)}}
```

If there is still a way to use the Date/Time format please let me know. It would be helpful to add it to the documentation also. 

--
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 117f7457-f439-e41e-8782-ff627e6b030b
* Version Independent ID: 22f86ac6-47f8-447f-82e9-8093b3ddf0fb
* Content: [Adaptive Cards Template Language - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/templating/language)
* Content Source: [AdaptiveCards/templating/language.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/templating/language.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by jwoo-msft** [comment]
@erwelch 
You can solve this problem using prebuilt functions we provide via Adaptive Expression Language.
We have an example you can try [here](
https://github.com/microsoft/AdaptiveCards/blob/jwoo/Template-visualizer-dotnet/samples/Templates/Elements/Template.Functions.DateFunctions.json).

formatDateTime function you see in the expression is a prebuilt function of [Adaptive Expression Language](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-adaptive-expressions?view=azure-bot-service-4.0).

You can learn more about AEL usage in template language by going [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-adaptive-expressions?view=azure-bot-service-4.0)

**Comment by erwelch** [comment]
@jwoo-msft thank you! Can this be added to documents, perhaps in the breaking changes section? It isn't clear that I can no longer use the previous Date/Time formatting and I should be using a built-in function instead.

**Comment by jwoo-msft** [comment]
> @jwoo-msft thank you! Can this be added to documents, perhaps in the breaking changes section? It isn't clear that I can no longer use the previous Date/Time formatting and I should be using a built-in function instead.

You can still use Date/Time formatting. formatDateTime is a new utility function that can be used to massage the time/date data into strict RFC 3389 format, so the data can be used for current Date/Time formatting function. And yes, your insight is correct. By using formatDateTime, you don't have to rely on Date/Time functions for your formatting need.

**Comment by erwelch** [comment]
@jwoo-msft  - yes I understand I can still use the Date/Time formatting, but I can no longer use it *without* the `formatDateTime` built-in function because `Expand` transforms my date time away from the strict RFC 3389 if I don't use the built-in function. This, in my opinion, is a breaking change.

**Comment by jwoo-msft** [comment]
@erwelch 

Thanks for reporting this issue. This is because Json.Net deserialized the date string into a data object, and it changed the format. You can use formatDateTime function for now, but this behavior will be corrected, so that it won't be a breaking change.

**Comment by jwoo-msft** [comment]
I'm closing this issue as this is fixed by [this PR](https://github.com/microsoft/AdaptiveCards/pull/4095)
