### ISSUE TITLE
Kevinbmxisaac

### ISSUE THREAD

**Issue by kevinbmx50** [MicrosoftDocs/AdaptiveCards#304]
{
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "Here is a ninja cat"
        },
        {
            "type": "Image",
            "url": "http://adaptivecards.io/content/cats/1.png"
        }
    ]
}

**Comment by matthidinger** [comment]
Dupe of #306
