### ISSUE TITLE
Kevin ochoa

### ISSUE THREAD

**Issue by kevinbmx50** [MicrosoftDocs/AdaptiveCards#306]
[Enter feedback here]

> `{Kevin ochoa}> 

    "type": "AdaptiveCard",{SRC2090244366}>
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "Here is a ninja cat"
        },
        {
            "type": "Image",
            "url": "http://adaptivecards.io/content/cats/1.png"
        Kevin Ochoa }
Ochoa    ]
Ubaldo quinonez}
    "version": "1.0",
    "body": [
        {Link/.com
(kevinbmx50@gmail.com)
(××××)
            "type": "TextBlock",
            "text": "Here is a ninja cat"
        },
        {
            "type": "Image",
            "url": "http://adaptivecards.io/content/cats/1.png"
        }
    ]
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 272125ec-d694-2abd-a879-d288f3d28934
* Version Independent ID: e5c34866-d43c-a204-f03c-677c5a646efe
* Content: [Getting Started - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/getting-started)
* Content Source: [AdaptiveCards/authoring-cards/getting-started.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/authoring-cards/getting-started.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by matthidinger** [comment]
Hi @kevinbmx50, this issue seems to be a bit malformed. If it was created in error no problem, we can close it. If not, please add some more details so we can try to resolve your problem. Thanks!
