### ISSUE TITLE
If function for color property results in a Parse Invalid Error

### ISSUE THREAD

**Issue by HiddenWithinOne** [MicrosoftDocs/AdaptiveCards#323]
Hello,
I am currently facing an issue where I cannot dynamically change the color of a text block from the values I get from my JSON payload. I want to use the built-in "if" function but that doesn't seem to work. Neither goes simply having the semantic values expected for the color property to be something I pull directly from the payload work.

Furthermore, I tried using one of the sample templates as an example, the Stock update sample to be specific. There it too has the color property being set using an if function. But when I try editing the sample in the adaptive cards designer, I get the same error.

I am using the 1.2 target version, in case you need that bit of info.

Looking to hear back from you regarding this issue. Thank you.
Dhruv Patel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 117f7457-f439-e41e-8782-ff627e6b030b
* Version Independent ID: 22f86ac6-47f8-447f-82e9-8093b3ddf0fb
* Content: [Adaptive Cards Template Language - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/templating/language)
* Content Source: [AdaptiveCards/templating/language.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/templating/language.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by matthidinger** [comment]
Hi there, can you provide the template payload and data you are using? And it doesn't work in the designer all? If you open the browser dev tools there should be an error in the console window that would help pinpoint what specifically is failing.

**Comment by HiddenWithinOne** [comment]
[StockUpdateSample.txt](https://github.com/MicrosoftDocs/AdaptiveCards/files/5125275/StockUpdateSample.txt)
[StockUpdateSamplePayload.txt](https://github.com/MicrosoftDocs/AdaptiveCards/files/5125276/StockUpdateSamplePayload.txt)

Hey, I've attached the sample codes I was trying to build off of. When I open these in the online Adaptive Cards Designer I get an error regarding the if statement that is used to change the color of the text fields. The specific error that the designer gives me is the following:
[Parse] Invalid value "${if(change >= 0, 'good', 'attention')}" for property "color"

Not sure if it is just an issue with the designer itself, or something to do with the code. Again, would really appreciate the feedback.

**Comment by matthidinger** [comment]
Thanks for following up, that is indeed a bug in the Designer. I've filed this bug to track the fix: https://github.com/microsoft/AdaptiveCards/issues/4658

The binding should work properly in actual usage via the SDKs, so please re-open and let us know if that isn't case.
