### ISSUE TITLE
How to apply multilingual adaptive card when using rendering SDK?

### ISSUE THREAD

**Issue by jychaaacha** [MicrosoftDocs/AdaptiveCards#375]
[Enter feedback here]

I am utilizing rendering SDK. (Android, Java script, iOS)
I want to use multilingual adaptive card, but rendering SDK doesn't support multilingual adaptive card.
I think it is because a data json doesn't work in rendering SDK.

Is there any other way to provide multilingual?
Or do you have a plan to support data json in rendering SDK?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4264cfd8-c15e-8ee8-b83c-9890597e67f8
* Version Independent ID: e1ffa3d4-b150-84a2-98f3-4d1bfd543952
* Content: [JavaScript SDK - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/javascript/getting-started)
* Content Source: [AdaptiveCards/sdk/rendering-cards/javascript/getting-started.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/sdk/rendering-cards/javascript/getting-started.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by johnmiroki** [comment]
This is the lacked feature that makes adaptive card short of "enterprise grade", so to speak. Any plan to catch up?
