### ISSUE TITLE
Universal Action Model Docs needs clarification on Invoke response format

### ISSUE THREAD

**Issue by Zenulous** [MicrosoftDocs/AdaptiveCards#388]
In the document, the response for the `adaptiveCard/action` Invoke activity is `application/vnd.microsoft.adaptive.card`. 

200 | application/vnd.microsoft.adaptive.card | Adaptive Card | The request was successfully processed, and the response includes an Adaptive Card that the client should display in place of the current one.
-- | -- | -- | --

However, on Teams using this type leads to the following error:

```json
{
  "statusCode": 200,
  "value": {
    "code": "200",
    "message": "Unexpected response type for Status Code: 200 Expected responseTypes: application/vnd.microsoft.card.adaptive or application/vnd.microsoft.activity.message"
  },
  "type": "application/vnd.microsoft.error",
  "text": null,
  "attachmentLayout": null,
  "channelData": null
}
``` 

I can't speak for other channels, but for teams the responseType has to be `application/vnd.microsoft.card.adaptive`, not `application/vnd.microsoft.adaptive.card`. I can't get the Invoke response to work otherwise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93584a54-8a69-aae2-e890-849d367040c2
* Version Independent ID: cd61793f-b330-9d8d-ebd0-8814f8aab3bd
* Content: [Universal Action Model - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/universal-action-model)
* Content Source: [AdaptiveCards/authoring-cards/universal-action-model.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/authoring-cards/universal-action-model.md)
* Product: **adaptive-cards**
* GitHub Login: @sowrabh-msft
* Microsoft Alias: **sonrs**

**Comment by sowrabh-msft** [comment]
This is indeed an error in documentation. `application/vnd.microsoft.card.adaptive` is the correct string to be used for response type. We'll fix the docs to indicate the same. Thanks for sharing this.
cc: @matthidinger @dclaux
