### ISSUE TITLE
Error with msTeams

### ISSUE THREAD

**Issue by Gnaullet** [MicrosoftDocs/AdaptiveCards#56]
Excuse me but i can't use the adapatative card for my Bot in teams. Return ERROR 400 Bad Request. Why this ? This adaptative card works in Bot framework emulator

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d5f1948-8ed0-f397-99ac-d10d8ae74d2b
* Version Independent ID: 63485280-4fee-678e-c5d4-5cd4b4dfd3bf
* Content: [Adaptive Cards for Bot Developers - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/get-started/bots)
* Content Source: [AdaptiveCards/get-started/Bots.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/get-started/Bots.md)
* Service: **unspecified**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by Gnaullet** [comment]
What do you want "by not yet supported" ?

**Comment by laslanian** [comment]
What is the current support for Adaptive Cards as of May 16, 2018? 
Current Status List page https://docs.microsoft.com/en-us/adaptive-cards/get-started/bots#channel-status was updated back in June 2017 which is almost a year ago, and is not current at all. Does this mean there have not been any updates to this?

**Comment by matthidinger** [comment]
Hi folks, good news: Microsoft Teams has announced Adaptive Card support in preview. It's getting close! :)

https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-features

**Comment by ashoksamal6363** [comment]
Is this the correct way to use it in a LUIS BOT C#?
I am getting error message that: Sorry, my bot code is having an issue. Please help!

[LuisIntent("ScheduleAnAppoitment")]
        public async Task ScheduleAnAppoitmentIntent(IDialogContext context, LuisResult result)
        {

            var replyMessage = context.MakeMessage();
            var json = await GetCardText("a");

            AdaptiveCardParseResult cardParseResult = AdaptiveCard.FromJson(json);

            replyMessage.Attachments.Add(new Attachment()
            {
                Content = cardParseResult.Card,
                ContentType = AdaptiveCard.ContentType,
                Name = "Card"
            });

            await context.PostAsync(replyMessage);

        }
        public async Task<string> GetCardText(string cardName)
        {
            var path = HostingEnvironment.MapPath($"/Cards/{cardName}.json");
            if (!File.Exists(path))
                return string.Empty;

            using (var f = File.OpenText(path))
            {
                return await f.ReadToEndAsync();
            }
        }
