### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by Gnaullet** [MicrosoftDocs/AdaptiveCards#57]
Are adaptive cards supported by teams? If not, what will it be?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db11bc3a-be2d-998f-0bfa-b2d70a33f2ef
* Version Independent ID: c05ee199-ad86-0c01-c9bf-9b226f36c841
* Content: [Adaptive Cards Partners - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/resources/partners)
* Content Source: [AdaptiveCards/resources/Partners.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/resources/Partners.md)
* Service: **unspecified**
* GitHub Login: @mollyd26
* Microsoft Alias: **modalton**

**Comment by Gnaullet** [comment]
I saw on the application: Teams app studio react code in the tab library control. I wanted to know if I could use it to return for example a checkbox in teams?

**Comment by praneethak** [comment]
when will Adaptive cards be available in Microsoft Teams platform? Any date?

**Comment by matthidinger** [comment]
Hi folks, good news! Microsoft Teams has just announced Adaptive Card support in preview :)

https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-features
