### ISSUE TITLE
Timeline is part of the April 2018 Update

### ISSUE THREAD

**Issue by EJ6612** [MicrosoftDocs/AdaptiveCards#60]
This page needs to be updated.
(4/30/18)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac6a6b28-6ce8-1674-9f26-64679825b3ad
* Version Independent ID: 2e2d2e6a-b8fe-2b8a-0580-291e42f26d1d
* Content: [Adaptive Cards for Windows Developers - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/get-started/windows#feedback)
* Content Source: [AdaptiveCards/get-started/Windows.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/get-started/Windows.md)
* Service: **unspecified**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by matthidinger** [comment]
Thanks! I've removed the preview notice :)
