### ISSUE TITLE
Windows Timeline (Spring Creators Update)

### ISSUE THREAD

**Issue by DDSoftDennie** [MicrosoftDocs/AdaptiveCards#62]
Is it please possible to show the full code to implement the code in UWP and timeline?
This code has unknown variables. Thanks, Dennie

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac6a6b28-6ce8-1674-9f26-64679825b3ad
* Version Independent ID: 2e2d2e6a-b8fe-2b8a-0580-291e42f26d1d
* Content: [Adaptive Cards for Windows Developers - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/get-started/windows)
* Content Source: [AdaptiveCards/get-started/Windows.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/get-started/Windows.md)
* Service: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by anbare** [comment]
Hi DDSoftDennie, please see the Timeline documentation: https://docs.microsoft.com/en-us/windows/uwp/launch-resume/useractivities

Thanks!
