### ISSUE TITLE
Embed type

### ISSUE THREAD

**Issue by shtefko** [MicrosoftDocs/AdaptiveCards#68]
There are several interesting presentation scenarios that could be achieved with card that embeds some website. This would not necessarily have to allow embedding of any website, but instead gradually add support for more popular ones (e.g. YouTube, Twitter, PowerBI etc.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ba3dbcc-00b5-1896-969e-71cd4385a7a3
* Version Independent ID: deaea059-3262-cc12-f45a-3346083d4b6a
* Content: [Adaptive Cards Roadmap - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/resources/future)
* Content Source: [AdaptiveCards/resources/Future.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/resources/Future.md)
* Service: **unspecified**
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by matthidinger** [comment]
Hi @shtefko - thanks for this feedback! We are actively looking into scenarios where great looking cards can be automatically generated based on the metadata from various websites, and then could be embedded in other experiences. Stay tuned and please keep the feedback coming!
