### ISSUE TITLE
Adaptive Card on Facebook

### ISSUE THREAD

**Issue by 1110770MiguelSilva** [MicrosoftDocs/AdaptiveCards#73]
I have been using AdaptiveCard on Facebook Messenger, using the rendered image, but now it's not working properly all of a sudden. The rendered image is not clickable and has a zoom that doesn't allow it to be seen in it's totality. Any idea on why this started happening?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db11bc3a-be2d-998f-0bfa-b2d70a33f2ef
* Version Independent ID: c05ee199-ad86-0c01-c9bf-9b226f36c841
* Content: [Adaptive Cards Partners - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/resources/partners)
* Content Source: [AdaptiveCards/resources/Partners.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/resources/Partners.md)
* Product: **adaptive-cards**
* GitHub Login: @mollyd26
* Microsoft Alias: **modalton**

**Comment by matthidinger** [comment]
Hi @1110770MiguelSilva - sorry about the troubles with the Messenger integration!

cc/ @EricDahlvang 

Can you provide us with more information to help out:
1. A screenshot if possible
2. The JSON the bot is sending
3. Do you know when this started? 
4. Any Bot ID or other information we can use to debug on our end?

**Comment by 1110770MiguelSilva** [comment]
[Facebook AdaptiveCard.zip](https://github.com/MicrosoftDocs/AdaptiveCards/files/2098992/Facebook.AdaptiveCard.zip)

Inside the zip is a screenshot of how it appears on FB Messenger, and how it appears on the Emulator, and the json that's sent. Most of the values are empty because they are filled with code.

Unfortunately I'm not sure when this started, but I think for like a month. And as for Bot ID I don't think there's anything I can give you, it's still in testing right now.

Thank you!

**Comment by EricDahlvang** [comment]
@1110770MiguelSilva The images you sent do not match the adaptive card .json you sent.  

Nonetheless, there does appear to be an issue with how the downrendered image is displayed in Messenger @matthidinger The top portion of this card is correctly down rendered (there are no numbers on the right, because the .json does not contain any numbers):

![image](https://user-images.githubusercontent.com/11055362/41433842-e781b7d4-6fce-11e8-9426-638705ebe4e6.png)


However, Messenger is not showing the entire image:

![image](https://user-images.githubusercontent.com/11055362/41433949-2280d022-6fcf-11e8-84fe-6a8e1a3b17d0.png)

**Comment by 1110770MiguelSilva** [comment]
@EricDahlvang How does it not match? If it's because some of the words on the json are not on the left column it's because in code I remove them if their correspondent value on the right is empty.

But yeah, that's the main issue, that it does not show the entire image. And before this problem the image was clickable, it was a "file" that was sent to the conversation, and could be expanded, now not even that, making it impossible to see it fully.

**Comment by anbare** [comment]
@EricDahlvang are you able to help more with this issue? Thanks!

**Comment by EricDahlvang** [comment]
@anbare There is nothing for me to do.  The image is downrendered correctly, but for some reason it is not being sized down to fill the top portion of the card.  This looks to me like a bug in the connector's conversion from Activity Schema to Messenger message.

**Comment by 1110770MiguelSilva** [comment]
@EricDahlvang Ok, thank you. Any idea where or who exactly should we try and contact, or create an issue, to try and resolve this? I guess it would be Microsoft's Bot Framework team?

**Comment by EricDahlvang** [comment]
@craigjensen  Is this something you can help with?

**Comment by craigjensen** [comment]
Facebook requires an aspect ratio of 1.91:1 or else it will scale/crop the image.  See: [here](https://developers.facebook.com/docs/messenger-platform/send-messages/template/generic)

**Comment by EricDahlvang** [comment]
@craigjensen  This image is being created from an Adaptive Card down render.  Here is the card:

```json
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "width": "auto",
          "items": [
            {
              "type": "Image",
              "size": "medium",
              "url": "https://weghobot.blob.core.windows.net/images/Wegho.png",
              "style": "person",
              "spacing": "none"
            }
          ]
        },
        {
          "type": "Column",
          "width": "stretch",
          "items": [
            {
              "type": "TextBlock",
              "text": "Tipo de Serviço",
              "horizontalAlignment": "right",
              "isSubtle": true,
              "size": "large"
            },
            {
              "type": "TextBlock",
              "text": "Limpeza Doméstica",
              "horizontalAlignment": "right",
              "spacing": "none",
              "size": "extralarge",
              "color": "accent"
            }
          ]
        }
      ]
    },
    {
      "type": "ColumnSet",
      "separator": true,
      "spacing": "medium",
      "columns": [
        {
          "type": "Column",
          "width": "stretch",
          "items": [
            {
              "type": "TextBlock",
              "text": "Data",
              "isSubtle": true,
              "weight": "bolder",
              "size": "extralarge"
            },
            {
              "type": "TextBlock",
              "text": "Hora",
              "isSubtle": true,
              "weight": "bolder",
              "size": "extralarge"
            },
            {
              "type": "TextBlock",
              "text": "Frequência",
              "isSubtle": true,
              "weight": "bolder",
              "size": "extralarge"
            },
            {
              "type": "TextBlock",
              "text": "Quartos",
              "isSubtle": true,
              "weight": "bolder",
              "size": "extralarge"
            },
            {
              "type": "TextBlock",
              "text": "Casas de Banho",
              "isSubtle": true,
              "weight": "bolder",
              "size": "extralarge"
            },
            {
              "type": "TextBlock",
              "text": "Código Postal",
              "isSubtle": true,
              "weight": "bolder",
              "size": "extralarge"
            },
            {
              "type": "TextBlock",
              "text": "Duração",
              "isSubtle": true,
              "weight": "bolder",
              "size": "extralarge"
            }
          ]
        },
        {
          "type": "Column",
          "width": "auto",
          "items": [
            {
              "type": "TextBlock",
              "text": "",
              "horizontalAlignment": "right",
              "size": "extralarge"
            },
            {
              "type": "TextBlock",
              "text": "",
              "horizontalAlignment": "right",
              "size": "extralarge"
            },
            {
              "type": "TextBlock",
              "text": "",
              "horizontalAlignment": "right",
              "size": "extralarge"
            },
            {
              "type": "TextBlock",
              "text": "",
              "horizontalAlignment": "right",
              "size": "extralarge"
            },
            {
              "type": "TextBlock",
              "text": "",
              "horizontalAlignment": "right",
              "size": "extralarge"
            },
            {
              "type": "TextBlock",
              "text": "",
              "horizontalAlignment": "right",
              "size": "extralarge"
            },
            {
              "type": "TextBlock",
              "text": "",
              "horizontalAlignment": "right",
              "size": "extralarge"
            }
          ]
        }
      ]
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "title": "Confirmar",
      "data": "Confirmar"
    },
    {
      "type": "Action.Submit",
      "title": "Alterar",
      "data": "Alterar"
    },
    {
      "type": "Action.Submit",
      "title": "Cancelar",
      "data": "Cancelar"
    }
  ]
}
```

**Comment by 1110770MiguelSilva** [comment]
And before the image sent was really a file, that could be clicked and zoomed, so the whole thing could be seen. But now since it's basically used as the image of an hero card it won't work like it did before.

**Comment by aforank** [comment]
> As a workaround for this problem, you can send an adaptive card without actions, and send the actions as part of a hero card. see this code example:
> `
> 
> ```
>         var adaptiveCard = card.AdaptiveCard;
>         var result= new List<Attachment>();
> 
>         //handle actions as regular actions - or else the image is displayed incorrectly
>         var cardButtons = adaptiveCard.Actions;
>         adaptiveCard.Actions = null;
> 
>         // Create the attachment.
>         Attachment adaptiveAttachment = new Attachment()
>         {
>             ContentType = AdaptiveCard.ContentType,
>             Content = adaptiveCard
>         };
> 
> 
> 
>         resualt.Add(adaptiveAttachment);
> 
>       
>         if (cardButtons.Any())
>         {
>             List<CardAction> replayButtons = new List<CardAction>();
>             foreach (AdaptiveSubmitAction button in cardButtons)
>             {
> 
>                 string OptionTitle = button.Title;
>                 string OptionReturnValue = button.Data.ToString();
>                 string optionType = BotReplayCardButtonType.imBack.ToString();
> 
>                 CardAction plButton = new CardAction()
>                 {
>                     Value = OptionReturnValue,
>                     Type = optionType,
>                     Title = OptionTitle
>                 };
>                 replayButtons.Add(plButton);
>             }
> 
>             var plCard = new HeroCard()
>             {
>                 Title = StringConstants.CHOOSE_OPTION,
>                 Buttons = replayButtons,
> 
>             };
> 
>             resualt.Add(plCard.ToAttachment());
>         }
> 
>           
>                 
> 
>             return result;`
> ```

How does this look after rendering on facebook?

**Comment by aforank** [comment]
@EricDahlvang Is there any plan for the fix?

**Comment by EricDahlvang** [comment]
@matthidinger this must be related to how an adaptive card is converted to a facebook message in the bot connector service. Should this be moved to https://github.com/Microsoft/BotFramework-Services ?

**Comment by aforank** [comment]
@EricDahlvang @matthidinger By the way the root cause of this issue is Action.Submit button. If we try to render an adaptive card with a button (Action.Submit) then it looses its aspect ratio. As a workaround, I am currently converting the adaptive card into an image using AdaptiveCard.Rendering.Wpf library myself by keeping the aspect ratio within the limits when there is an extra button in the card.

**Comment by andrewleader** [comment]
Thanks @aforank for the investigation, so just to confirm, even when using the AdaptiveCard.Rendering.Wpf library, if a Action.Submit button is included, the aspect ratio is lost?

**Comment by aforank** [comment]
@andrewleader I did some more investigation. Looks like it's not a problem with aspect ratio alone, rather it's the issue with Hero card + Incorrect aspect ratio.

So if I try to create an adaptive card without Action.Submit. Bot service renders it like an individual image which appears absolutely fine even if the aspect ratio is incorrect (See below)

![image](https://user-images.githubusercontent.com/19813442/58701028-6a7bc800-83bf-11e9-8882-c4a2931d9e1b.png)

But if I create an adaptive card with Action.Submit. Bot service creates a hero card and places the image inside it, and that's where the problem is. Facebook expects image inside an hero card to be 1:91, which is not in this case.

![image](https://user-images.githubusercontent.com/19813442/58701314-32c15000-83c0-11e9-8807-afefbd833738.png)


As a workaround, I convert the card into an image using AdaptiveCard.Rendering.Wpf, but I do not include the Action.Submit object, otherwise the button also appears as an image. So I exclude the button, create an image and then generate a hero card with that button and image. However, I still have to convert the card into image twice. First time, I check the original width and height and see If the aspect ratio is correct or not. If not, then I have to add "n" number of empty text blocks in the card and then again convert it so it appears fine.

![image](https://user-images.githubusercontent.com/19813442/58701365-55536900-83c0-11e9-8daf-aacc47aa2d4b.png)
