### ISSUE TITLE
Render2Image

### ISSUE THREAD

**Issue by 1110770MiguelSilva** [MicrosoftDocs/AdaptiveCards#74]
Is the Render2Image available anywhere? From what I can see the webpage doesn't exist anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cde9faa1-d627-7878-dc8c-d011ca1d7a79
* Version Independent ID: 13b04120-abf1-a545-bdaf-d3c919db14ea
* Content: [Adaptive Cards Tools - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/resources/tools)
* Content Source: [AdaptiveCards/resources/Tools.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/resources/Tools.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by matthidinger** [comment]
Thanks for reporting, the link has been updated and should be refreshed shortly
