### ISSUE TITLE
When Adaptive card supports for MS Teams?

### ISSUE THREAD

**Issue by levotragiang** [MicrosoftDocs/AdaptiveCards#79]
Hi,
I'm diving in developing a Bot with MS Teams channel, my bot will be deployed both on PC and mobile Teams app. However, when I intended to create a card which allows users to pick a date time, then I have no idea with it. I've searched a lot about Adaptive Cards and O365 Connector Cards, but only O365 Connector Card work for me because Adaptive cards are only supporting in Dev Preview version at present. 
I just wondered when Adaptive card supports for MS Teams? It will really helps me a lot.

Thanks in advance! :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d5f1948-8ed0-f397-99ac-d10d8ae74d2b
* Version Independent ID: 63485280-4fee-678e-c5d4-5cd4b4dfd3bf
* Content: [Adaptive Cards for Bot Developers - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/get-started/bots)
* Content Source: [AdaptiveCards/get-started/Bots.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/get-started/Bots.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by anbare** [comment]
Hi levotragiang,

The preview of Microsoft Teams [currently supports Cards](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-reference#cards-supported-in-teams) as you noticed.

You'll want to reach out to the Microsoft Teams team to find out when they are going to officially release Cards support (you can post a question on their docs linked). Thanks!
