### ISSUE TITLE
Add Input.Password

### ISSUE THREAD

**Issue by live-abhishek** [MicrosoftDocs/AdaptiveCards#80]
Can we have a new input type for password type of fields. It can be helpful to get the user credentials directly from the bot itself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4dc7404b-3d6c-01bc-568b-746835e4a471
* Version Independent ID: 8a4bacfa-deef-f1e2-74e4-41899ad3d409
* Content: [Card Schema - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/create/cardschema)
* Content Source: [AdaptiveCards/create/CardSchema.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/create/CardSchema.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by matthidinger** [comment]
Hi @live-abhishek, thanks for the suggestion! We have a discussion going on this topic at the link below, please feel free to add your comments there:

https://github.com/Microsoft/AdaptiveCards/issues/1443
