### ISSUE TITLE
Is Type really not required?

### ISSUE THREAD

**Issue by luke-simmons** [MicrosoftDocs/AdaptiveCards#83]
Most of the elements say that "type" is not required - is this correct? i.e. How can you create a TextBlock if you do not set the type to "TextBlock"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4dc7404b-3d6c-01bc-568b-746835e4a471
* Version Independent ID: 8a4bacfa-deef-f1e2-74e4-41899ad3d409
* Content: [Card Schema - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/card-schema#textblock)
* Content Source: [AdaptiveCards/authoring-cards/card-schema.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/authoring-cards/card-schema.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by matthidinger** [comment]
Good catch, indeed it is required, and the description says that it "Must be X" - but in some cases the required column says No. I'll file an issue to update this!
