### ISSUE TITLE
Very sparse documentation

### ISSUE THREAD

**Issue by AlexKven** [MicrosoftDocs/AdaptiveCards#86]
This documentation doesn't say anything about how to override any behavior or rendering, i.e., what exactly do you have to do to, say, change which DOM elements are used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e393760-d7c6-c5e7-bf99-54e65197fee7
* Version Independent ID: e8935c21-d80f-1825-768f-ade4a80b83c0
* Content: [Extensibility - JavaScript SDK - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/javascript/extensibility#custom-element-rendering)
* Content Source: [AdaptiveCards/sdk/rendering-cards/javascript/extensibility.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/sdk/rendering-cards/javascript/extensibility.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by alonronin** [comment]
There is no documentation at all about the architecture, which make you wonder if this is something that microsoft wants us to use.

From looking at the code, you need to create an `Element` Class and to extend the `CardElement` Class.

Check out how they register its own elements: https://github.com/Microsoft/AdaptiveCards/blob/309263ac87cfce0595633f72a69272ec975a911d/source/nodejs/adaptivecards/src/card-elements.ts#L5584

And how to create a Card Element such as Image: 
https://github.com/Microsoft/AdaptiveCards/blob/309263ac87cfce0595633f72a69272ec975a911d/source/nodejs/adaptivecards/src/card-elements.ts#L1373

**Comment by matthidinger** [comment]
Thanks for the feedback here folks. We've just published a more detailed update (in TypeScript) but hopefully it helps. Please let us know and re-open if you have additional feedback!

https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/javascript/extensibility
