### ISSUE TITLE
Code sample on UWP Client

### ISSUE THREAD

**Issue by SigmaSolutions** [MicrosoftDocs/AdaptiveCards#87]
Would it be possible to provide a code sample on UWP client to demonstrate how the adaptive card be rendered? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c035094-2d63-5a8c-9dcc-243bffc93619
* Version Independent ID: fa889e53-904a-0680-6308-d3162ea22ef5
* Content: [UWP SDK - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/uwp/getting-started)
* Content Source: [AdaptiveCards/sdk/rendering-cards/uwp/getting-started.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/sdk/rendering-cards/uwp/getting-started.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by matthidinger** [comment]
Hi @SigmaSolutions please see here for a C# code sample: https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/uwp/render-a-card

Let us know if that doesn't answer you question
