### ISSUE TITLE
Code sample on .NET HTML Client on rendering adaptive card

### ISSUE THREAD

**Issue by SigmaSolutions** [MicrosoftDocs/AdaptiveCards#88]
Would .NET HTML rendering also apply to Razor page of MVC?

Would it be possible to provide a code sample on .NET HTML client to demonstrate how the adaptive card be rendered? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c348ba6f-1189-5529-8607-e6607d6fc5a5
* Version Independent ID: 0dd3f499-aea4-69d1-c2a7-79105f7b18d2
* Content: [.NET HTML SDK - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/net-html/getting-started)
* Content Source: [AdaptiveCards/sdk/rendering-cards/net-html/getting-started.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/sdk/rendering-cards/net-html/getting-started.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by matthidinger** [comment]
You could call the renderer API from a Razor View if you want to inject the HTML in it. I don't have a code sample but it should be relatively straight forward using Razor's docs to call APIs

Please see here for a C# sample: https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/net-html/render-a-card

Please let us know if that doesn't answer your question

**Comment by PeggyWiltz** [comment]
This documentation shows how to create the html in the c# class but not how to display it on the page.  The Razor documentation is not helpful either. Just adding the razor page to this example in the documentation would be extremely helpful.

**Comment by uncheckederror** [comment]
@PeggyWiltz I believe you need to wrap this line:
```cs
@renderedCard.Html
```
In the raw HTML helper that Razor provides as follows:
```cs
@Html.Raw(renderedCard.Html)
```
You can review the docs for this method here: [https://docs.microsoft.com/en-us/dotnet/api/system.web.mvc.htmlhelper.raw?view=aspnet-mvc-5.2](https://docs.microsoft.com/en-us/dotnet/api/system.web.mvc.htmlhelper.raw?view=aspnet-mvc-5.2)
