### ISSUE TITLE
Coming "soon"

### ISSUE THREAD

**Issue by MijoBarbaric** [MicrosoftDocs/AdaptiveCards#89]
Hi guys,

What does coming "soon" mean? Over a year has passed since there was an update on native styling for UWP. Thanks in advance for any hints!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 832aa87c-25f7-7ff5-a74d-d0ca97fac18f
* Version Independent ID: 11fe7db5-ebad-89a3-6d89-e5d2dc63b644
* Content: [Native styling - UWP SDK - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/uwp/native-styling)
* Content Source: [AdaptiveCards/sdk/rendering-cards/uwp/native-styling.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/sdk/rendering-cards/uwp/native-styling.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by matthidinger** [comment]
Sorry for the delay here, we've got some docs up now :)
