### ISSUE TITLE
MS Teams Adaptive Cards Support [Question]

### ISSUE THREAD

**Issue by andregouveia8** [MicrosoftDocs/AdaptiveCards#91]
**Hello Everyone,**

I need to know when **Adaptive Cards** is supported for **_MS Teams_** **_(NodeJS)_**.
Now the state is "Coming Soon".

Does anyone know when the state is "coming soon"? 

Thanks 👍

**Comment by levotragiang** [comment]
It's now supporting officially. You can find out [here](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-reference) for more info.

Hope this helps!

**Comment by matthidinger** [comment]
Please give Teams a go and let us know if you run into any issues!
