### ISSUE TITLE
metadata

### ISSUE THREAD

**Issue by bw-kforce-ms** [MicrosoftDocs/AdaptiveCards#99]
Can we add an object in card scope for metadata that would be ignored by renderers but could be used by hosts for behavior extensions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc77860e-7ebe-609f-4700-67650dc44ade
* Version Independent ID: f21764e7-90b6-2a26-534f-e109bc39f697
* Content: [Implementing a Renderer - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/rendering-cards/implement-a-renderer)
* Content Source: [AdaptiveCards/rendering-cards/implement-a-renderer.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/rendering-cards/implement-a-renderer.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by matthidinger** [comment]
Yes indeed, you can pass along additional properties on any element and on the renderer side of things, a host app could use them to enhance the rendering. In the .NET library all types have an `AdditionalProperties` dictionary which will be serialized into the JSON. Our docs are a bit light on the renderer side, but as you're rendering a given element you can extract properties from the JSON (even non-standard ones) and use them to tailor the rendering. Please re-open if you'd like more info!
